import json
import urllib.request
import urllib.error

import os
SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://imthqokhjfanzhdihvsc.supabase.co")
API_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]

opportunities = [
    {
        "title": "Bourse Mathématiques au féminin",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-04-15",
        "source_url": "https://urlr.me/jMWSp7",
        "short_description": "Bourse de 11 000 € destinée aux étudiantes en Licence 3 de mathématiques dans les universités franciliennes (Mathematics and Physics, Economics, etc.).",
        "eligibility_summary": "Étudiantes en Licence 3 de mathématiques dans les universités d'Île-de-France. Réservé aux femmes.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse EFELIA-MIAI — Université Grenoble Alpes",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-04-30",
        "source_url": "https://urlr.me/Yb8Td7",
        "short_description": "Bourse de 10 000 € pour les étudiants en Licence 3 et Master en mathématiques, informatique, IA et électronique à l'Université Grenoble Alpes.",
        "eligibility_summary": "Licence 3 ou Master en mathématiques, informatique, IA, électronique à l'Université Grenoble Alpes.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse FMJHCare — Paris-Saclay & Institut Polytechnique de Paris",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2026-06-14",
        "source_url": "https://urlr.me/3JhtbF",
        "short_description": "Bourse de 11 000 € pour des études en mathématique fondamentale ou appliquée à Paris-Saclay ou à l'Institut Polytechnique de Paris.",
        "eligibility_summary": "Étudiants en Licence ou Master en mathématiques (fondamentale ou appliquée) à Paris-Saclay ou à l'Institut Polytechnique de Paris.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Maryam Mirzakhani — Mathématiques",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-01-30",
        "source_url": "https://urlr.me/HKBaTm",
        "short_description": "Bourse de 11 000 € en Master (et jusqu'à 82 800 € en Doctorat) en mathématiques et applications (finance, santé, IA, etc.) en France.",
        "eligibility_summary": "Étudiants en Master ou Doctorat en mathématiques et leurs applications. Clôture annuelle le 30 janvier.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse MINT — Toulouse Capitole",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-02-09",
        "source_url": "https://urlr.me/XCFBZx",
        "short_description": "Bourse de 10 000 € pour un Master en Mathématiques, Innovation et Informatique à l'Université Toulouse Capitole.",
        "eligibility_summary": "Candidats en Master en mathématiques, innovation ou informatique à l'Université Toulouse Capitole.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse AIMS South Africa × Google DeepMind — IA pour la Science",
        "country": "afrique",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-03-01",
        "source_url": "https://urlr.me/SU95n6",
        "short_description": "Bourse de financement complet pour un Master en Sciences Mathématiques (filière AI for Science) à l'AIMS en Afrique du Sud, en partenariat avec Google DeepMind.",
        "eligibility_summary": "Diplômés en mathématiques, sciences ou informatique souhaitant poursuivre un Master à l'AIMS Afrique du Sud. Programme AI for Science.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse EUR Spectrum — Sciences & Ingénierie",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-04-04",
        "source_url": "https://urlr.me/8aVHGF",
        "short_description": "Bourse de 10 000 € pour un Master en mathématiques, chimie moléculaire, physique, sciences de la Terre ou ingénierie.",
        "eligibility_summary": "Candidats en Master en mathématiques, chimie moléculaire, physique, sciences de la Terre ou ingénierie dans une université partenaire Spectrum.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Institut Galilée — Master & Ingénieur",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2026-06-12",
        "source_url": "https://urlr.me/RjMP7p",
        "short_description": "Bourse de 10 500 € pour un Master ou diplôme d'ingénieur en mathématiques, informatique et filières connexes à l'Institut Galilée.",
        "eligibility_summary": "Étudiants en Master ou cycle ingénieur en mathématiques, informatique et sciences à l'Institut Galilée (Université Sorbonne Paris Nord).",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse ESOP — ETH Zurich",
        "country": "suisse",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2026-11-30",
        "source_url": "https://urlr.me/8atzwe",
        "short_description": "Bourse de 24 000 CHF pour un Master en mathématiques, mathématiques appliquées, statistiques ou finances quantitatives à l'ETH Zurich.",
        "eligibility_summary": "Candidats exceptionnels en Master en mathématiques, statistiques ou finance quantitative. Clôture le 30 novembre.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Graduate Programs PSL — Mathématiques & Informatique",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2026-12-11",
        "source_url": "https://urlr.me/bvDfyV",
        "short_description": "Bourse de 12 000 € pour un Master en Mathématiques, Informatique, Finance ou Management dans les établissements de l'Université PSL.",
        "eligibility_summary": "Candidats en Master dans les établissements PSL (ENS Paris, Dauphine, Mines ParisTech, etc.). Domaines : maths, informatique, finance, management.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Sélection Internationale ENS Ulm — Sciences",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2026-12-15",
        "source_url": "https://urlr.me/JFmSGU",
        "short_description": "Bourse de 12 000 € pour des Masters en Mathématiques, Biologie, Chimie ou Physique à l'ENS Ulm de Paris.",
        "eligibility_summary": "Étudiants internationaux en Master en sciences exactes (mathématiques, biologie, chimie, physique) à l'ENS Ulm.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Henri Lebesgue — Mathématiques",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://urlr.me/8WcQfV",
        "short_description": "Bourse de 10 000 € pour des formations en mathématiques fondamentales et appliquées dans les universités d'Angers, Brest, Le Mans, Nantes ou Rennes.",
        "eligibility_summary": "Étudiants en L3 ou Master en mathématiques dans les universités d'Angers, Brest, Le Mans, Nantes ou Rennes.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse IRMIA++ / Mobil-iti — Mathématiques Strasbourg",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "partielle",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://irmiapp.unistra.fr/fr/formation/bourses-de-master",
        "short_description": "Bourse de plus de 7 000 € pour des Masters en Mathématiques Fondamentales, Statistique, Calcul Scientifique, Mathématiques de l'Information ou Actuariat à Strasbourg.",
        "eligibility_summary": "Étudiants en Master en mathématiques fondamentales, statistique, calcul scientifique ou actuariat à l'Université de Strasbourg.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Labex Milyon — Mathématiques & Informatique Lyon",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://milyon.universite-lyon.fr/bourses--47496.kjsp",
        "short_description": "Bourse de 10 000 € pour des parcours de mathématiques ou d'informatique dans les établissements de l'Université de Lyon (L3 et Master).",
        "eligibility_summary": "Étudiants en L3 ou Master en mathématiques ou informatique dans les établissements de l'Université de Lyon.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse PERSYVAL — Mathématiques & Informatique Grenoble",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://persyval.univ-grenoble-alpes.fr/bourses-master",
        "short_description": "Bourse de 8 000 € pour un Master en Mathématiques Fondamentales, Operations Research, Combinatorics and Optimization à Grenoble Alpes.",
        "eligibility_summary": "Candidats en Master en mathématiques fondamentales, recherche opérationnelle ou optimisation à l'Université Grenoble Alpes.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Graduate School UGA — Sciences & IA",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://urlr.me/tYTHJh",
        "short_description": "Bourse de 16 000 € pour un Master en mathématiques, physique, chimie, informatique ou intelligence artificielle à l'Université Grenoble Alpes.",
        "eligibility_summary": "Étudiants en Master en mathématiques, physique, chimie, informatique ou IA à l'Université Grenoble Alpes (Graduate School).",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Graduate+ — Université de Lyon",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-01-23",
        "source_url": "https://graduate-plus.fr/bourses-dexcellence/",
        "short_description": "Bourse de 10 000 à 12 000 € pour un Master en mathématiques, informatique, ingénierie, physique ou sciences sociales dans les établissements de l'Université de Lyon.",
        "eligibility_summary": "Étudiants en Master en mathématiques, informatique, ingénierie, physique ou sciences sociales à l'Université de Lyon. Clôture le 23 janvier.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse SMARTS-UP — Data, IA & Mathématiques — Paris Cité",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-01-15",
        "source_url": "https://mobility.smarts-up.fr/",
        "short_description": "Bourse de 10 000 € pour un Master en Mathématiques, Data Science, Biostatistiques ou Intelligence Artificielle à l'Université Paris Cité.",
        "eligibility_summary": "Étudiants en Master en mathématiques, data science, biostatistiques ou IA à l'Université Paris Cité. Clôture le 15 janvier.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse PhD Tracks — Institut Polytechnique de Paris",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-01-20",
        "source_url": "https://urlr.me/gUjeKB",
        "short_description": "Bourse de 10 000 € pour un Master suivi d'un Doctorat en mathématiques, informatique, IA, mécanique ou physique à l'Institut Polytechnique de Paris.",
        "eligibility_summary": "Étudiants en Master (avec parcours doctorat) en mathématiques, informatique, IA, mécanique ou physique à l'Institut Polytechnique de Paris.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Ampère — ENS Lyon",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-01-23",
        "source_url": "https://tinyurl.com/AMperus",
        "short_description": "Bourse de 12 000 € pour un Master en sciences exactes, lettres ou sciences humaines et sociales à l'ENS Lyon.",
        "eligibility_summary": "Candidats en Master en sciences exactes (incluant mathématiques), lettres ou sciences humaines à l'ENS Lyon. Clôture le 23 janvier.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse d'Excellence — EPFL",
        "country": "suisse",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-03-31",
        "source_url": "https://urlr.me/5GRwKe",
        "short_description": "Bourse de 20 000 CHF pour toutes les formations de Master à l'EPFL, incluant les mathématiques appliquées et statistiques.",
        "eligibility_summary": "Candidats d'excellence pour n'importe quel Master à l'EPFL. Domaines éligibles : mathématiques appliquées, informatique, ingénierie, sciences, etc. Clôture le 31 mars.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse IN-WBI / WBI — Wallonie-Bruxelles International",
        "country": "belgique",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-03-31",
        "source_url": "https://urlr.me/JcDqW7",
        "short_description": "Bourse de 10 000 € pour un Master en mathématiques, ingénierie biomédicale, sciences de gestion et autres disciplines en Wallonie ou à Bruxelles.",
        "eligibility_summary": "Candidats en Master en mathématiques, ingénierie ou sciences de gestion dans une université de Wallonie ou de Bruxelles. Clôture le 31 mars.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse IdEx Paris-Saclay — Excellence Master",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-03-15",
        "source_url": "https://urlr.me/suAEqg",
        "short_description": "Bourse de 10 000 € pour toutes les formations de Master à Paris-Saclay, incluant Mathématiques Vision Apprentissage et Analyse Modélisation Simulation.",
        "eligibility_summary": "Étudiants en Master dans n'importe quelle filière à l'Université Paris-Saclay. Clôture en mars.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse King Abdulaziz University (KAU)",
        "country": "international",
        "category": "bourse",
        "study_level": "tous",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-01-31",
        "source_url": "https://kau.edu.sa/en/page/scholarship",
        "short_description": "Bourse du gouvernement saoudien pour des études en mathématiques, informatique, génie et d'autres disciplines à l'Université King Abdulaziz.",
        "eligibility_summary": "Candidats internationaux souhaitant étudier en mathématiques, informatique, ingénierie ou autres disciplines à la KAU, Arabie Saoudite. Clôture le 31 janvier.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Mastercard Foundation — University of the Western Cape",
        "country": "afrique",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "sciences_tech",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://www.uwc.ac.za/study/postgraduate/scholarships",
        "short_description": "Bourse de financement complet pour des étudiants africains en Natural Sciences (Mathematical Sciences) et autres disciplines à l'Université du Western Cape en Afrique du Sud.",
        "eligibility_summary": "Étudiants africains en sciences naturelles (mathématiques), éducation scientifique ou disciplines connexes à l'Université du Western Cape.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse CSC — China Scholarship Council",
        "country": "chine",
        "category": "bourse",
        "study_level": "tous",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-03-01",
        "source_url": "https://urlr.me/rmaZPH",
        "short_description": "Bourses du gouvernement chinois couvrant toutes les formations dispensées dans les universités chinoises, à l'exception de la médecine. Deadline variable, autour de février-mars.",
        "eligibility_summary": "Candidats souhaitant étudier dans une université chinoise partenaire. Toutes disciplines sauf médecine. Niveau licence, master ou doctorat.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse MFA — Gouvernement Roumain (Étude en Roumanie)",
        "country": "europe",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2027-03-31",
        "source_url": "https://scholarships.studyinromania.gov.ro/",
        "short_description": "Bourses du Ministère des Affaires Étrangères roumain pour des études de Licence, Master ou Doctorat dans les universités roumaines. Toutes disciplines sauf médecine et pharmacie.",
        "eligibility_summary": "Candidats souhaitant étudier en Roumanie. Toutes disciplines éligibles sauf médecine et pharmacie. Niveau licence, master ou doctorat. Clôture fin mars.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Master Mind — Flandre & Bruxelles",
        "country": "belgique",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://urlr.me/nu97y2",
        "short_description": "Bourse de 10 020 € pour des programmes de Master dans les universités de Flandre ou de Bruxelles. Deadline variable, à partir du 15 janvier.",
        "eligibility_summary": "Étudiants internationaux postulant à n'importe quel programme de Master dans une université de Flandre ou de Bruxelles.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Marie Skłodowska-Curie Actions (MSCA)",
        "country": "europe",
        "category": "bourse",
        "study_level": "bac5",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://marie-sklodowska-curie-actions.ec.europa.eu/",
        "short_description": "Bourse européenne de plus de 50 000 € pour des chercheurs en Doctorat ou Post-Doctorat dans tous les domaines scientifiques. Deadline variable.",
        "eligibility_summary": "Chercheurs en début de carrière (doctorat) ou post-doctorat dans n'importe quel domaine scientifique. Programme financé par l'Union Européenne.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse UTLN — Université de Toulon",
        "country": "france",
        "category": "bourse",
        "study_level": "tous",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": "2026-12-05",
        "source_url": "https://urlr.me/XTu5rP",
        "short_description": "Bourse de 10 000 € pour toutes les formations de l'Université de Toulon (sauf les formations en alternance). Clôture le 5 décembre.",
        "eligibility_summary": "Étudiants internationaux postulant à n'importe quelle formation à l'Université de Toulon (hors alternance). Clôture le 5 décembre.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse Mistral — Université d'Avignon",
        "country": "france",
        "category": "bourse",
        "study_level": "tous",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://urlr.me/uh7NPj",
        "short_description": "Bourse de 6 000 € pour toutes les formations à l'Université d'Avignon.",
        "eligibility_summary": "Étudiants internationaux postulant à n'importe quelle formation à l'Université d'Avignon.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse M2 Internationale — Université de La Rochelle",
        "country": "france",
        "category": "bourse",
        "study_level": "bac5",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://urlr.me/Aepub7",
        "short_description": "Bourse de 6 000 € pour tous les Masters 2 (M2) de l'Université de La Rochelle.",
        "eligibility_summary": "Étudiants internationaux postulant à un Master 2 dans n'importe quelle discipline à l'Université de La Rochelle.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
    {
        "title": "Bourse ORION — Master Recherche en Lorraine",
        "country": "france",
        "category": "bourse",
        "study_level": "bac3",
        "domain": "multidisciplinaire",
        "funding_type": "complete",
        "budget_required": 0,
        "deadline": None,
        "source_url": "https://urlr.me/krsHuJ",
        "short_description": "Bourse de 10 000 € pour n'importe quel M2 de recherche ou cycle ingénieur en Lorraine.",
        "eligibility_summary": "Étudiants internationaux postulant à un M2 de recherche ou un cycle ingénieur dans une école ou université de Lorraine.",
        "is_active": True,
        "location": None,
        "competitiveness_level": None,
    },
]

print(f"Nombre d'opportunités à insérer : {len(opportunities)}")

payload = json.dumps(opportunities).encode("utf-8")

req = urllib.request.Request(
    f"{SUPABASE_URL}/rest/v1/opportunities",
    data=payload,
    method="POST",
    headers={
        "apikey": API_KEY,
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    },
)

try:
    with urllib.request.urlopen(req) as response:
        status = response.status
        body = response.read().decode("utf-8")
        inserted = json.loads(body)
        print(f"Statut HTTP : {status}")
        print(f"Nombre de records insérés : {len(inserted)}")
        print("Titres insérés :")
        for i, rec in enumerate(inserted, 1):
            print(f"  {i:02d}. [id={rec.get('id')}] {rec.get('title')}")
except urllib.error.HTTPError as e:
    error_body = e.read().decode("utf-8")
    print(f"Erreur HTTP {e.code}: {e.reason}")
    print(f"Détail : {error_body}")
except Exception as e:
    print(f"Erreur inattendue : {e}")
